/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wysaid_ndkopenglbackdraw_GLHelpFunctions */

#ifndef _Included_org_wysaid_ndkopenglbackdraw_GLHelpFunctions
#define _Included_org_wysaid_ndkopenglbackdraw_GLHelpFunctions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wysaid_ndkopenglbackdraw_GLHelpFunctions
 * Method:    getGLBackDrawImage
 * Signature: (Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_org_wysaid_ndkopenglbackdraw_GLHelpFunctions_getGLBackDrawImage
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
